### ISSUE TITLE
Not friendly with webpack-hot-middleware?

### ISSUE THREAD

**Issue by sheldhur** [theKashey/react-imported-component#160]
I see that the update comes, but DOM doesn't update

**webpack.dev.babel.js**
```js
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');

module.exports = require('./webpack.base.babel')({
  mode: 'development',
  entry: [
    'eventsource-polyfill',
    'webpack-hot-middleware/client?reload=true',
    path.join(process.cwd(), 'app/app.js')
  ],
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js'
  },
  plugins: [
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
      inject: true, 
      template: 'app/index.html'
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, 
      failOnError: false
    }),
    new webpack.DefinePlugin({
      'process.env': {
        REAL_API_URL: JSON.stringify(process.env.API_URL),
      }
    })
  ],
  devtool: 'eval-source-map',
  performance: {
    hints: false
  }
});
```

![image](https://user-images.githubusercontent.com/4166193/69115022-2346d800-0ac2-11ea-8698-1dbbb4f0d7dd.png)
![image](https://user-images.githubusercontent.com/4166193/69115170-a5370100-0ac2-11ea-9a3a-0d46f2d53613.png)
![image](https://user-images.githubusercontent.com/4166193/69115045-335eb780-0ac2-11ea-9d3a-c01395920001.png)

**Comment by theKashey** [comment]
Root cause - `RIC` "caches" `imports` from call to call, one of the reasons why it might provide a hook based API.
And that cache persist during the hot update, so you see the same component you saw before.

The only exception - React-Hot-Loader. RIC detect hot-update and flushes cache for a current component.

Solutions:
- expose `clearImportedCache`, you could manually call on HMR
- `useLoadable` right now has  build in  HMR (executeLoadableEventually), however, it works only for the "second view". And this moment shall be improved a bit.

**Comment by theKashey** [comment]
In would be super cool to use different `marks` for different `updates`, so on HMR mark would magically change, magically causing updates.
Unfortunately, that's not a "pure", and would break SSR, which is not the point :)
