### ISSUE TITLE
When to use LazyBoundary in application?

### ISSUE THREAD

**Issue by Arczi88** [theKashey/react-imported-component#225]
Hello,

When to use the LazyBoundary component? I don't understand if it should be each time when I am lazy importing components or maybe I should wrap the entire application into the LazyBoundary component?
And what exactly LazyBoundary component does? It has fallback JSX property where usually I put `null` value.
So far I understand it as some kind of fallback for a time of lazy loading components, ex. for a spinning loader to indicate the user that his/her action is in progress...
But only what I really want is to keep the existing UI until the component will be fully lazy-loaded and then change UI. And so far in 99% it happens.

Thanks

**Comment by theKashey** [comment]
I should update documentation or, better, update the internal logic, but in short `LazyBoundary` is something, you should use instead of `Suspense` for React <18, when `Suspense` is not rendered on the server.

For `React>=18` you should use real `Suspense`.

Keep in mind - this is only related to SSR, the server rendering and hydration to the rendering result.
In both cases using a wrong option, and __today__ `LazyBoundary` is a wrong option for `React 18`, will lead to a total failure.
