### ISSUE TITLE
Usage when React is embeded into server-side app

### ISSUE THREAD

**Issue by pkrefta** [theKashey/react-imported-component#87]
Hi,

I've an application running on `http://myapp.local` - and it's a Django based. On one of it's pages I'm using a React component with simple piece of code
```
<div id="root"></div>
<script src="http://localhost:3000/static/js/bundle.js"></script>
<script src="http://localhost:3000/static/js/main.chunk.js"></script>
```
and devserver running on `http://localhost:3000`

My component is getting quite big and I'm trying to split the code so I've added
```
import importedComponent from 'react-imported-component';
const SomeComponent = importedComponent( () => import('./SomeComponent'))
```
It compiles fine but it tries to load chunk from `http://myapp.local/static/js/1.chunk.js` instead of using `localhost:3000`. Is there any way to configure this, force hostname or something like that ?

**Comment by theKashey** [comment]
Yes, but only via "your bundler" configuration.
`Parcel` does not have this issue by design, so you are probably using webpack, which also should not have a problem unless you configured it in a wrong way.

It should be something like `publicPath` - try to search for `myapp.local`, as long as you are overriding defaults with this value.
